### ISSUE TITLE
API Test Extension

### ISSUE THREAD

**Issue by ChillySpiral** [ChillySpiral/SWENG#11]
- Extend the Unit Tests to the API

**Comment by JohnX451** [comment]
Changes stored in branch `11-api-test-extension` (based on `feature/#11_FastAPI`)
- reworked existing tests to fit FastAPI object model
- added new test file for REST API tests (only one test so far, waiting for finished API to implement further tests)

**Comment by JohnX451** [comment]
closed with merge
